// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SupraSeguros.Services.Agents.DbContexts;

#nullable disable

namespace SupraSeguros.Services.Agents.Migrations
{
    [DbContext(typeof(AgentsDbContext))]
    [Migration("20240726175545_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Agente", b =>
                {
                    b.Property<Guid>("AgenteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CodigoAgente")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AgenteId");

                    b.ToTable("Agente");
                });

            modelBuilder.Entity("PolizaAgente", b =>
                {
                    b.Property<Guid>("PolizaAgenteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AgenteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("FechaAsignacion")
                        .HasColumnType("date");

                    b.Property<Guid?>("PolizaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PolizaAgenteId");

                    b.ToTable("PolizaAgente");
                });
#pragma warning restore 612, 618
        }
    }
}
