// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SupraSeguros.Services.Policy.DbContexts;

#nullable disable

namespace SupraSeguros.Services.Policy.Migrations
{
    [DbContext(typeof(PolicyDbContext))]
    [Migration("20240726152535_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SupraSeguros.Services.Policy.Entities.Cobertura", b =>
                {
                    b.Property<Guid>("CoberturaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LimiteMaximo")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("CoberturaId");

                    b.ToTable("Cobertura");
                });

            modelBuilder.Entity("SupraSeguros.Services.Policy.Entities.Poliza", b =>
                {
                    b.Property<Guid>("PolizaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Deducible")
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeroPoliza")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Prima")
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("TipoSeguro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PolizaId");

                    b.ToTable("Poliza");
                });

            modelBuilder.Entity("SupraSeguros.Services.Policy.Entities.PolizaCobertura", b =>
                {
                    b.Property<Guid>("PolizaCoberturaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CoberturaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("MontoCubierto")
                        .HasColumnType("decimal(6,2)");

                    b.Property<Guid>("PolizaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PolizaCoberturaId");

                    b.ToTable("PolizaCobertura");
                });
#pragma warning restore 612, 618
        }
    }
}
